#!/bin/bash
# Publish a skill to ClawHub from its folder.
# Reads name, version, and published flag from SKILL.md frontmatter.
#
# Usage: ./scripts/publish.sh <skill-folder>
# Example: ./scripts/publish.sh skills/fastloop
#
# Safety:
#   - Skills publish by default. Add `published: false` to SKILL.md frontmatter
#     to opt OUT (mirrors npm's `private: true` convention).
#   - Refuses if clawhub.json has `"publish": false`
#   - Slug comes from `name:` field (no folder name guessing)
#   - Version comes from `version:` field (matches --version flag)
#   - Copies full directory (no missing files)
#   - Checks if version already exists before publishing

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <skill-folder>"
  echo "Example: $0 skills/fastloop"
  exit 1
fi

SKILL_DIR="$1"
SKILL_MD="$SKILL_DIR/SKILL.md"

# For the global skill.md (lowercase), support both
if [ ! -f "$SKILL_MD" ] && [ -f "$SKILL_DIR/skill.md" ]; then
  SKILL_MD="$SKILL_DIR/skill.md"
fi

if [ ! -f "$SKILL_MD" ]; then
  echo "❌ No SKILL.md found in $SKILL_DIR"
  exit 1
fi

# Parse frontmatter (between --- lines)
FRONTMATTER=$(sed -n '/^---$/,/^---$/p' "$SKILL_MD" | sed '1d;$d')

get_field() {
  echo "$FRONTMATTER" | grep "^$1:" | head -1 | sed "s/^$1:[[:space:]]*//" | sed 's/^["'"'"']//' | sed 's/["'"'"']$//' || echo ""
}

# Look up a key nested under a top-level YAML block (e.g. metadata.version).
# Extracts the block spanning `^<block>:` to the next non-indented line, then
# grabs the indented `<key>:` value. Works on BSD + GNU awk/sed.
get_nested_field() {
  local block="$1" key="$2"
  echo "$FRONTMATTER" | awk -v block="$block" '
    $0 ~ "^"block":[[:space:]]*$" { in_block=1; next }
    in_block && /^[^[:space:]]/   { in_block=0 }
    in_block                       { print }
  ' | grep -E "^[[:space:]]+$key:" | head -1 \
    | sed -E "s/^[[:space:]]+$key:[[:space:]]*//" \
    | sed 's/^["'"'"']//' | sed 's/["'"'"']$//' || echo ""
}

NAME=$(get_field "name")
# version: prefer top-level (older skills, also documented in clawhub
# skill-format.md as the canonical location); fall back to metadata.version
# (newer skills generated by simmer-skill-builder put it there). Most modern
# skills in skills/ are metadata-only, which is why the publish step had been
# bailing — every recent skill failed the "No 'version:' field" guard.
VERSION=$(get_field "version")
if [ -z "$VERSION" ]; then
  VERSION=$(get_nested_field "metadata" "version")
fi
PUBLISHED=$(get_field "published")

if [ -z "$NAME" ]; then
  echo "❌ No 'name:' field in $SKILL_MD frontmatter"
  exit 1
fi

if [ -z "$VERSION" ]; then
  echo "❌ No 'version:' field in $SKILL_MD frontmatter"
  exit 1
fi

# Publishing defaults to true. Only refuse if explicitly opted out.
# (Of 18 skills in skills/ at 2026-05-18, only 1 had an explicit `published:`
#  field — the prior opt-in guard was performative and forced every other
#  publish to bypass this script entirely.)
if [ "$PUBLISHED" = "false" ]; then
  echo "❌ Skill '$NAME' is marked 'published: false' in $SKILL_MD"
  echo "   Remove or flip the flag if you intend to publish."
  exit 1
fi

# Second guard: honor clawhub.json "publish": false
CLAWHUB_JSON="$SKILL_DIR/clawhub.json"
if [ -f "$CLAWHUB_JSON" ]; then
  PUBLISH_FLAG=$(python3 -c "import json,sys; print(json.load(open('$CLAWHUB_JSON')).get('publish', True))" 2>/dev/null || echo "True")
  if [ "$PUBLISH_FLAG" = "False" ]; then
    REASON=$(python3 -c "import json; print(json.load(open('$CLAWHUB_JSON')).get('publish_reason', 'no reason given'))" 2>/dev/null || echo "unknown")
    echo "❌ Skill '$NAME' is marked 'publish: false' in clawhub.json"
    echo "   Reason: $REASON"
    echo "   Remove the flag from clawhub.json if you intend to publish."
    exit 1
  fi
fi

echo "📦 Publishing $NAME@$VERSION"
echo "   Source: $SKILL_DIR"

# Check if version already exists
echo "   Checking ClawHub for existing version..."
if npx clawhub@latest inspect "$NAME" 2>&1 | grep -q "Latest: $VERSION"; then
  echo "❌ Version $VERSION already exists on ClawHub"
  echo "   Bump the version in $SKILL_MD and try again"
  exit 1
fi

# Copy full directory to temp (using slug as folder name)
TMP_DIR="/tmp/$NAME"
rm -rf "$TMP_DIR"
cp -r "$SKILL_DIR" "$TMP_DIR"

# Clean up unwanted files. The old top-level-only rm missed NESTED caches
# (e.g. tests/__pycache__), so a stale 90KB .pyc shipped in the copytrader
# 0.1.1 bundle. Prune every __pycache__ dir + loose .pyc/.pyo recursively.
find "$TMP_DIR" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
find "$TMP_DIR" -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete 2>/dev/null || true
rm -rf "$TMP_DIR"/.* 2>/dev/null || true

FILE_COUNT=$(find "$TMP_DIR" -type f | wc -l)
echo "   Files: $FILE_COUNT"
# Portable file listing (BSD find on macOS doesn't support `-printf`).
# Was: find "$TMP_DIR" -type f -printf "   - %P (%s bytes)\n"
# `find -exec` + `stat` works on both BSD (macOS) and GNU (Linux). The
# `set -euo pipefail` at the top of the script halted the publish on
# the previous `find -printf` failure (2026-05-12), leaving the
# subsequent `clawhub publish` step unreached — so callers had to do
# the publish step manually.
( cd "$TMP_DIR" && find . -type f | while read -r f; do
    size=$(wc -c < "$f" | tr -d ' ')
    echo "   - ${f#./} ($size bytes)"
  done )

# Publish
echo "   Publishing..."
# `|| EXIT_CODE=$?` keeps set -e from killing the script before the
# error report below prints (a bare `clawhub` binary missing from PATH died
# silently at exactly this line on 2026-06-12).
EXIT_CODE=0
OUTPUT=$(npx clawhub@latest publish "$TMP_DIR" --version "$VERSION" --owner simmer 2>&1) || EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  echo "✅ Published $NAME@$VERSION"
  echo "   $OUTPUT"
else
  echo "❌ Publish failed:"
  echo "   $OUTPUT"
  exit 1
fi

# Cleanup
rm -rf "$TMP_DIR"
