#!/usr/bin/env python3
"""Vendor the pure replay-engine modules from the simmer backend into the SDK.

SIM-3070 slice 2. The `simmer backtest` CLI runs the SAME engine the internal
`scripts/replay_run.py run-bundle` uses, but the SDK is published to PyPI and
can't depend on the private backend. So we vendor a SMALL, public-safe subset
of `simmer_v3/replay/` into `simmer_sdk/backtest/replay/`.

Vendored set (8 modules — pure engine, no DB/redis/boto3, no badge scoring, no
secret thresholds):

    store, simstate, server, engine, harness, duckdb_store,
    candles_service, feeds/binance

DELIBERATELY EXCLUDED (managed badge/worker pipeline — not public-safe, not used
by the local CLI): catalog, worker, queue, reverify, report_store, tape_capture,
strategies.

Each vendored file gets a provenance header pinning the backend commit it was
copied from. The vendored tree is a generated artifact: do not hand-edit it.
To resync after the backend engine changes:

    python scripts/sync_replay_engine.py --source /path/to/simmer

CI can run this with `--check` to fail when the vendored copy has drifted from
the pinned `--source` checkout (engine-drift mitigation, plan.md Risks).
"""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path

# (relative path under simmer_v3/replay) -> stays the same under backtest/replay
VENDORED = [
    "store.py",
    "simstate.py",
    "server.py",
    "engine.py",
    "harness.py",
    "duckdb_store.py",
    "candles_service.py",
    "feeds/binance.py",
]

# Package __init__ files we author here (NOT copied from the backend, since the
# backend's replay/__init__ re-exports the same public names but lives in a
# different package). Kept minimal + provenance-free so they don't churn.
INIT_FILES = {
    "__init__.py": (
        '"""Vendored Simmer replay engine (SIM-3070).\n\n'
        "Pure backtest substrate copied from the simmer backend's\n"
        "``simmer_v3/replay`` package. Generated by\n"
        "``scripts/sync_replay_engine.py`` — do not hand-edit.\n"
        '"""\n\n'
        "from .store import (\n"
        "    HistoricalStore,\n"
        "    MarketMeta,\n"
        "    PricePoint,\n"
        "    Resolution,\n"
        "    ReplayView,\n"
        "    TradePrint,\n"
        ")\n\n"
        '__all__ = [\n'
        '    "HistoricalStore",\n'
        '    "MarketMeta",\n'
        '    "PricePoint",\n'
        '    "Resolution",\n'
        '    "ReplayView",\n'
        '    "TradePrint",\n'
        "]\n"
    ),
    "feeds/__init__.py": (
        '"""Vendored historical-feed stores (Binance klines plane)."""\n'
    ),
}


def _source_sha(source: Path) -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(source), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _header(rel: str, sha: str) -> str:
    short = sha[:12]
    return (
        f"# vendored from simmer_v3/replay/{rel} @ {short}\n"
        f"# DO NOT EDIT HERE — regenerate via scripts/sync_replay_engine.py\n"
    )


def _render(src_file: Path, rel: str, sha: str) -> str:
    """Original module body with a provenance header prepended.

    A leading comment block before the module docstring is legal — the docstring
    only needs to be the first *statement*, and comments aren't statements.
    """
    return _header(rel, sha) + src_file.read_text()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    here = Path(__file__).resolve().parents[1]  # simmer-sdk/
    default_source = here.parent / "simmer"
    ap.add_argument(
        "--source",
        default=str(default_source),
        help="path to the simmer backend checkout (default: ../simmer)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="don't write; exit non-zero if the vendored copy has drifted",
    )
    args = ap.parse_args()

    source = Path(args.source).resolve()
    replay_src = source / "simmer_v3" / "replay"
    if not replay_src.is_dir():
        sys.exit(f"no simmer_v3/replay under {source}")

    dest = here / "simmer_sdk" / "backtest" / "replay"
    sha = _source_sha(source)

    drifted = []
    for rel in VENDORED:
        src_file = replay_src / rel
        if not src_file.exists():
            sys.exit(f"missing source module: {src_file}")
        rendered = _render(src_file, rel, sha)
        dest_file = dest / rel
        if args.check:
            current = dest_file.read_text() if dest_file.exists() else ""
            # Ignore the @ <sha> line: the body is what must match, and the sha
            # legitimately differs across syncs. Compare everything else.
            if _strip_sha(current) != _strip_sha(rendered):
                drifted.append(rel)
                diff = difflib.unified_diff(
                    _strip_sha(current).splitlines(),
                    _strip_sha(rendered).splitlines(),
                    fromfile=f"vendored/{rel}",
                    tofile=f"backend/{rel}",
                    lineterm="",
                )
                print("\n".join(list(diff)[:40]))
        else:
            dest_file.parent.mkdir(parents=True, exist_ok=True)
            dest_file.write_text(rendered)

    for rel, body in INIT_FILES.items():
        dest_file = dest / rel
        if args.check:
            current = dest_file.read_text() if dest_file.exists() else ""
            if current != body:
                drifted.append(rel)
        else:
            dest_file.parent.mkdir(parents=True, exist_ok=True)
            dest_file.write_text(body)

    if args.check:
        if drifted:
            print(f"\nDRIFT: {len(drifted)} vendored file(s) differ from {sha[:12]}: "
                  + ", ".join(drifted))
            return 1
        print(f"vendored replay engine in sync with backend @ {sha[:12]}")
        return 0

    print(f"vendored {len(VENDORED)} modules + {len(INIT_FILES)} package files "
          f"from {source} @ {sha[:12]} -> {dest.relative_to(here)}")
    return 0


def _strip_sha(text: str) -> str:
    """Drop the provenance header's `@ <sha>` line so drift compares bodies."""
    return "\n".join(
        ln for ln in text.splitlines()
        if not ln.startswith("# vendored from simmer_v3/replay/")
    )


if __name__ == "__main__":
    raise SystemExit(main())
