name: "Security: Secret Scanning"

on:
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog
        uses: trufflesecurity/trufflehog@e64309e4514a601c7d23f336688782a229a4a754
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified --fail
